# Copyright 2018, TCMC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default login/pass: Admin / zabbix

# Zabbix MySQL variables
mysql_db_host: "localhost"
zabbix_db: "zabbixdb"
zabbix_db_host: "%"
zabbix_db_user: "zabbixUser"
zabbix_db_pass: "zabbixPass"

# Deployment mode: "server" or "client"
zabbix_mode: "server"

# Zabbix Vars
zabbix_server: "localhost"
zabbix_server_name: "Custom Monitoring"

zabbix_server_ip: "127.0.0.1"

# PHP Date Timezone
php_date_timezone: "America/Toronto"
