# Copyright 2018, TCMC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Creating OpenStack Nova User and Role
  environment: "{{ admin_openrc_env }}"
  command: "{{ item }}"
  with_items:
   - openstack user create --domain default --password "{{ service_password }}" --email "nova@{{ os_dns_domain }}" nova
   - openstack role add --project service --user nova --user-domain default admin


- name: Creating OpenStack Nova Service
  environment: "{{ admin_openrc_env }}"
  command: "{{ item }}"
  with_items:
   - openstack service create --name nova --description "OpenStack Compute" compute


- name: Creating OpenStack Nova Endpoint
  environment: "{{ admin_openrc_env }}"
  command: "{{ item }}"
  with_items:
   - openstack endpoint create --region "{{ region }}" compute public "{{ endpoint_public_uri }}{{ compute_endpoint_public }}:8774/v2.1"
   - openstack endpoint create --region "{{ region }}" compute internal "{{ endpoint_internal_uri }}{{ compute_endpoint_internal }}:8774/v2.1"
   - openstack endpoint create --region "{{ region }}" compute admin "{{ endpoint_internal_uri }}{{ compute_endpoint_internal }}:8774/v2.1"
