# Copyright 2018, TCMC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: host - apt installing QEmu/KVM Hypervisor - Server
  apt: name={{item}} state=latest
  with_items:
    - ovmf
    - qemu-kvm
    - python-lxml
    - libvirt-daemon-system
  when: ubuntu_install == 'server'


- name: host - apt installing QEmu/KVM Hypervisor - Desktop
  apt: name={{item}} state=latest
  with_items:
    - ovmf
    - qemu-kvm
    - python-lxml
    - virt-viewer
    - virt-manager
    - spice-client-gtk
  when: ubuntu_install == 'desktop'


#- name: host - virsh wiping out default network
#  shell: virsh net-destroy default ; virsh undefine default
#  ignore_errors: yes


- name: host - group add regular system user to Libvirt/KVM groups
  user: name={{ regular_system_user }} groups=libvirt,kvm append=yes


# Review:
#- name: "Reconfiguring Libvirt and enabling VHOST_NET + KSM at the Compute Node (QEmu-KVM)"
#  command: "{{item}}"
#  with_items:
#    - sed -i 's/^VHOST_NET_ENABLED=0/VHOST_NET_ENABLED=1/' /etc/default/qemu-kvm
#    - sed -i 's/^KSM_ENABLED=AUTO/KSM_ENABLED=1/' /etc/default/qemu-kvm
#    - sed -i 's/^#listen_tls = 0/listen_tls = 0/' /etc/libvirt/libvirtd.conf
#    - sed -i 's/^#listen_tcp = 1/listen_tcp = 1/' /etc/libvirt/libvirtd.conf
#    - sed -i 's/^#auth_tcp = "sasl"/auth_tcp = "none"/' /etc/libvirt/libvirtd.conf
#    - sed -i 's/^env libvirtd_opts="-d"/env libvirtd_opts="-d -l"/' /etc/init/libvirt-bin.conf
#    - sed -i 's/^libvirtd_opts="-d"/libvirtd_opts="-d -l"/' /etc/default/libvirt-bin
#  notify: restart-libvirt-bin
