# Copyright 2018, TCMC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# References:
# https://docs.openstack.org/neutron/rocky/install/controller-install-ubuntu.html#configure-networking-options

- name: Installing Neutron Agents
  apt: name={{item}} state=latest
  with_items:
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
  notify: restart-neutron-agents

- name: Installing Neutron Linux Bridge Agent
  apt: name=neutron-linuxbridge-agent state=latest
  when: os_neutron_lbr_enabled == 'yes'
  notify: restart-neutron-lbr

- name: Installing Neutron Open vSwitch Agent
  apt: name=neutron-openvswitch-agent state=latest
  when: os_neutron_ovs_enabled == 'yes'
  notify: restart-neutron-ovs


- name: Updating neutron.conf
  template: src={{os_release}}/neutron.conf.j2
            dest=/etc/neutron/neutron.conf
            owner=root
            group=neutron
            mode=0640
            backup=yes
  when: item.os_project == "neutron"
  with_items: '{{mysql_databases}}'


- name: Updating linuxbridge_agent.ini
  template: src={{os_release}}/ml2/linuxbridge_agent.ini.j2
            dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini
            owner=root
            group=neutron
            mode=0640
            backup=yes
  when: os_neutron_lbr_enabled == 'yes'
  notify: restart-neutron-lbr


- name: Updating openvswitch_agent.ini
  template: src={{os_release}}/ml2/openvswitch_agent.ini.j2
            dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini
            owner=root
            group=neutron
            mode=0640
            backup=yes
  when: os_neutron_ovs_enabled == 'yes'
  notify: restart-neutron-ovs


- name: Updating dhcp_agent.ini
  template: src={{os_release}}/dhcp_agent.ini.j2
            dest=/etc/neutron/dhcp_agent.ini
            owner=root
            group=neutron
            mode=0644
            backup=yes
  notify: restart-neutron-agents


#- name: Updating dnsmasq-neutron.conf
#  copy: src=dnsmasq-neutron.conf
#        dest=/etc/neutron/dnsmasq-neutron.conf
#        owner=root
#        group=neutron
#        mode=0644
#        backup=yes
#  notify: restart-neutron-agents


- name: Updating l3_agent.ini
  template: src={{os_release}}/l3_agent.ini.j2
            dest=/etc/neutron/l3_agent.ini
            owner=root
            group=neutron
            mode=0644
            backup=yes
  notify: restart-neutron-agents


- name: Updating metadata_agent.ini
  template: src={{os_release}}/metadata_agent.ini.j2
            dest=/etc/neutron/metadata_agent.ini
            owner=root
            group=neutron
            mode=0644
            backup=yes
  notify: restart-neutron-agents


- name: Updating fwaas_driver.ini
  template: src={{os_release}}/fwaas_driver.ini.j2
            dest=/etc/neutron/fwaas_driver.ini
            owner=root
            group=neutron
            mode=0644
            backup=yes
  notify: restart-neutron-server


- name: Write custom sysctl.conf
  copy: src=sysctl.conf
        dest=/etc/sysctl.conf
        owner=root
        group=root
        mode=0644
        backup=yes
  when: os_neutron_lbr_enabled == 'yes'
  notify: reload-sysctl
