# Copyright 2018, TCMC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- stat: path=/home/{{regular_system_user}}/Downloads/svnfv-7.50.0021-vpl-1-centos7-amd64-disk1.qcow2c
  register: svnfv_image_register

- name: uploading svnfv-7.50.0021-vpl-1-centos7-amd64-disk1.qcow2c
  environment: "{{admin_openrc_env}}"
  os_image:
    name: nfv-7.50.0021-vpl-1-centos7-amd64
    is_public: yes
    container_format: bare
    disk_format: qcow2
    state: present
    filename: /home/{{regular_system_user}}/Downloads/svnfv-7.50.0021-vpl-1-centos7-amd64-disk1.qcow2c
    properties:
      cpu_arch: x86_64
  when: svnfv_image_register.stat.exists == True


- stat: path=/home/{{regular_system_user}}/Downloads/sveng-7.70.0017-vpl-1-centos7-amd64-disk1.qcow2c
  register: sveng_image_register

- name: uploading sveng-7.70.0017-vpl-1-centos7-amd64-disk1.qcow2c
  environment: "{{admin_openrc_env}}"
  os_image:
    name: eng-7.70.0017-vpl-1-centos7-amd64
    is_public: yes
    container_format: bare
    disk_format: qcow2
    state: present
    filename: /home/{{regular_system_user}}/Downloads/sveng-7.70.0017-vpl-1-centos7-amd64-disk1.qcow2c
    properties:
      cpu_arch: x86_64
  when: sveng_image_register.stat.exists == True


- stat: path=/home/{{regular_system_user}}/Downloads/svdba-6.65.0136-vpl-1-centos6-amd64-disk1.qcow2c
  register: svdba_image_register

- name: uploading svdba-6.65.0136-vpl-1-centos6-amd64-disk1.qcow2c
  environment: "{{admin_openrc_env}}"
  os_image:
    name: dba-6.65.0136-vpl-1-centos6-amd64
    is_public: yes
    container_format: bare 
    disk_format: qcow2
    state: present
    filename: /home/{{regular_system_user}}/Downloads/svdba-6.65.0136-vpl-1-centos6-amd64-disk1.qcow2c
    properties:
      cpu_arch: x86_64
  when: svdba_image_register.stat.exists == True


- stat: path=/home/{{regular_system_user}}/Downloads/ubuntu-18.04-server-cloudimg-amd64.img
  register: ubuntu18_image_register

- name: uploading "ubuntu-18.04-amd64"
  environment: "{{admin_openrc_env}}"
  os_image:
    name: ubuntu-18.04-amd64
    is_public: yes
    container_format: bare 
    disk_format: qcow2
    state: present
    filename: /home/{{regular_system_user}}/Downloads/ubuntu-18.04-server-cloudimg-amd64.img
    properties:
      cpu_arch: x86_64
  when: ubuntu18_image_register.stat.exists == True


- stat: path=/home/{{regular_system_user}}/Downloads/ubuntu-16.04-server-cloudimg-amd64-disk1.img
  register: ubuntu16_image_register

- name: uploading "ubuntu-16.04-amd64"
  environment: "{{admin_openrc_env}}"
  os_image:
    name: ubuntu-16.04-amd64
    is_public: yes
    container_format: bare 
    disk_format: qcow2
    state: present
    filename: /home/{{regular_system_user}}/Downloads/ubuntu-16.04-server-cloudimg-amd64-disk1.img
    properties:
      cpu_arch: x86_64
  when: ubuntu16_image_register.stat.exists == True


- stat: path=/home/{{regular_system_user}}/Downloads/ubuntu-14.04-server-cloudimg-amd64-disk1.img
  register: ubuntu14_image_register

- name: uploading "ubuntu-14.04-amd64"
  environment: "{{admin_openrc_env}}"
  os_image:
    name: ubuntu-14.04-amd64
    is_public: yes
    container_format: bare 
    disk_format: qcow2
    state: present
    filename: /home/{{regular_system_user}}/Downloads/ubuntu-14.04-server-cloudimg-amd64-disk1.img
    properties:
      cpu_arch: x86_64
  when: ubuntu14_image_register.stat.exists == True


- stat: path=/home/{{regular_system_user}}/Downloads/debian-9-openstack-amd64.qcow2
  register: debian9_image_register

- name: uploading "debian-9-amd64"
  environment: "{{admin_openrc_env}}"
  os_image:
    name: debian-9-amd64
    is_public: yes
    container_format: bare 
    disk_format: qcow2
    state: present
    filename: /home/{{regular_system_user}}/Downloads/debian-9-openstack-amd64.qcow2
    properties:
      cpu_arch: x86_64
  when: debian9_image_register.stat.exists == True


- stat: path=/home/{{regular_system_user}}/Downloads/CentOS-7-x86_64-GenericCloud.qcow2c
  register: centos7_image_register

- name: uploading "centos-7-amd64"
  environment: "{{admin_openrc_env}}"
  os_image:
    name: centos-7-amd64
    is_public: yes
    container_format: bare 
    disk_format: qcow2
    state: present
    filename: /home/{{regular_system_user}}/Downloads/CentOS-7-x86_64-GenericCloud.qcow2c
    properties:
      cpu_arch: x86_64
  when: centos7_image_register.stat.exists == True


- stat: path=/home/{{regular_system_user}}/Downloads/CentOS-6-x86_64-GenericCloud.qcow2c
  register: centos6_image_register

- name: uploading "centos-6-amd64"
  environment: "{{admin_openrc_env}}"
  os_image:
    name: centos-6-amd64
    is_public: yes
    container_format: bare 
    disk_format: qcow2
    state: present
    filename: /home/{{regular_system_user}}/Downloads/CentOS-6-x86_64-GenericCloud.qcow2c
    properties:
      cpu_arch: x86_64
  when: centos6_image_register.stat.exists == True


- stat: path=/home/{{regular_system_user}}/Downloads/Fedora-Cloud-Base-25-1.3.x86_64.qcow2
  register: fedora25_image_register

- name: uploading "fedora-25-amd64"
  environment: "{{admin_openrc_env}}"
  os_image:
    name: fedora-25-amd64
    is_public: yes
    container_format: bare
    disk_format: qcow2
    state: present
    filename: /home/{{regular_system_user}}/Downloads/Fedora-Cloud-Base-25-1.3.x86_64.qcow2
    properties:
      cpu_arch: x86_64
  when: fedora25_image_register.stat.exists == True


- stat: path=/home/{{regular_system_user}}/Downloads/cirros-0.3.4-x86_64-disk.img
  register: cirros_image_register

- name: uploading "cirros-0.3.4-amd64"
  environment: "{{admin_openrc_env}}"
  os_image:
    name: cirros-0.3.4-amd64
    is_public: yes
    container_format: bare 
    disk_format: qcow2
    state: present
    filename: /home/{{regular_system_user}}/Downloads/cirros-0.3.4-x86_64-disk.img
    properties:
      cpu_arch: x86_64
  when: cirros_image_register.stat.exists == True
